{% set name = "sdds" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdds-{{ version }}.tar.gz
  sha256: e16cf40563664726d5c905ec75d60367f887342ea9dabd24658911decd98f755

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.19.0
    - python >=3.6

test:
  imports:
    - sdds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pylhc/sdds
  summary: Python 3 package to handle SDDS files.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A Python package for I/O functionality with SDDS files.
  doc_url: https://pylhc.github.io/sdds/

extra:
  recipe-maintainers:
    - fsoubelet
